name: build
concurrency: "${{ github.head_ref || github.run_id || github.ref_name || github.ref }}-${{github.workflow}}"
on:
  workflow_dispatch:
  workflow_call:
  schedule: [{ cron: "0 4 * * *" }]
  push:
    branches: [main]
    paths:
      - Dockerfile
      - .dockerignore
      - "**/go.mod"
      - "**/go.sum"
      - "*.go"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@d5234d6605774d496731c394511848830d37a200

      - name: login to ghcr.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@210d783f42dfbd5492271c72e5f4232408f1d169
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |-
            # branch event
            type=ref,event=branch
            # tag event
            type=ref,event=tag
            # pull request event
            type=ref,event=pr

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - id: build-and-push
        uses: docker/build-push-action@48888e0b1305dca3a741ceb3b5a04ea336cd2626
        with:
          context: "."
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          labels: |-
            org.opencontainers.image.title=${{ github.workflow }}
            org.opencontainers.image.url=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.version=${{ github.ref_name }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=UNLICENSED
