name: Build
on:
  workflow_call:
  schedule: [{ cron: "0 4 * * *" }]
  push:
    branches: [main]
    paths:
      - "Dockerfile"
      - ".dockerignore"
      - "go.sum"
      - "*.go"
jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: "${{ github.head_ref || github.run_id || github.ref_name || github.ref }}-${{github.job}}"
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2

      - name: login to ghcr.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |-
            # branch event
            type=ref,event=branch
            # tag event
            type=ref,event=tag
            # pull request event
            type=ref,event=pr

      - uses: docker/build-push-action@v3
        with:
          context: "."
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          labels: |-
            org.opencontainers.image.title=${{ github.workflow }}
            org.opencontainers.image.url=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.version=${{ github.ref_name }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=UNLICENSED

  test:
    needs: [build]
    uses: ./.github/workflows/test.yml
