name: test
concurrency: "${{ github.head_ref || github.run_id || github.ref_name || github.ref }}-${{github.workflow}}"
on:
  workflow_dispatch:
  workflow_call:
  schedule: [{ cron: "0 4 * * *" }]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: login to ghcr.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - uses: ./
        id: self
        with:
          val: foo

      - {if: always(), run: "#pretty-print github.*\njq -SreC '.' <<'__JSON_DATA__'\n${{ toJSON(github) }}\n__JSON_DATA__\n", shell: bash}
      - {if: always(), run: "#pretty-print inputs.*\njq -SreC '.' <<'__JSON_DATA__'\n${{ toJSON(inputs) }}\n__JSON_DATA__\n", shell: bash}
      - {if: always(), run: "#pretty-print job.*\n   jq -SreC '.' <<'__JSON_DATA__'\n${{ toJSON(job) }}\n__JSON_DATA__\n", shell: bash}
      - {if: always(), run: "#pretty-print env.*\n   jq -SreC '.' <<'__JSON_DATA__'\n${{ toJSON(env) }}\n__JSON_DATA__\n", shell: bash}
      - {if: always(), run: "#pretty-print steps.*\n jq -SreC '.' <<'__JSON_DATA__'\n${{ toJSON(steps) }}\n__JSON_DATA__\n", shell: bash}
      - {if: always(), run: "#pretty-print runner.*\njq -SreC '.' <<'__JSON_DATA__'\n${{ toJSON(runner) }}\n__JSON_DATA__\n", shell: bash}
